Feature: Break Chrome with a timeout error
  This will attempt to reproduce the "Timeout" error in Chrome

  Background:

  Scenario Outline: Break it
    When I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    And I go to the first page
    And I go to the second page
    Examples:
      | Iteration |
      | 1         |
      | 2         |
      | 3         |
      | 4         |
      | 4         |
      | 6         |
      | 7         |
      | 8         |
      | 9         |
      | 10        |
      | 11        |
      | 12        |
      | 13        |
      | 14        |
      | 14        |
      | 16        |
      | 17        |
      | 18        |
      | 19        |
      | 20        |
      | 21        |
      | 22        |
      | 23        |
      | 24        |
      | 24        |
      | 26        |
      | 27        |
      | 28        |
      | 29        |
      | 30        |
      | 31        |
      | 32        |
      | 33        |
      | 34        |
      | 34        |
      | 36        |
      | 37        |
      | 38        |
      | 39        |
      | 40        |
      | 41        |
      | 42        |
      | 43        |
      | 44        |
      | 44        |
      | 46        |
      | 47        |
      | 48        |
      | 49        |
      | 50        |
      | 51        |
      | 52        |
      | 53        |
      | 54        |
      | 54        |
      | 56        |
      | 57        |
      | 58        |
      | 59        |
      | 60        |
      | 61        |
      | 62        |
      | 63        |
      | 64        |
      | 64        |
      | 66        |
      | 67        |
      | 68        |
      | 69        |
      | 70        |
      | 71        |
      | 72        |
      | 73        |
      | 74        |
      | 74        |
      | 76        |
      | 77        |
      | 78        |
      | 79        |
      | 80        |
      | 81        |
      | 82        |
      | 83        |
      | 84        |
      | 84        |
      | 86        |
      | 87        |
      | 88        |
      | 89        |
      | 90        |
      | 91        |
      | 92        |
      | 93        |
      | 94        |
      | 94        |
      | 96        |
      | 97        |
      | 98        |
      | 99        |
      | 100       |

